// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVkVUnzA7yyMI991yx1bozPilBA1j4FbQ',
    appId: '1:878896224913:web:a14e4be0a90be5a01abd30',
    messagingSenderId: '878896224913',
    projectId: 'travel-journal-beb23',
    authDomain: 'travel-journal-beb23.firebaseapp.com',
    databaseURL: 'https://travel-journal-beb23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-beb23.firebasestorage.app',
    measurementId: 'G-KNH8XCZEZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIlLlDNHuJ80HDDeTgueB9wTNvXbEB_Y',
    appId: '1:878896224913:android:a7e969c7cf2b6da81abd30',
    messagingSenderId: '878896224913',
    projectId: 'travel-journal-beb23',
    databaseURL: 'https://travel-journal-beb23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-beb23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM0UqyS2fDOEOx1zbZQTpssumm4wUlcas',
    appId: '1:878896224913:ios:316efce5054df4c01abd30',
    messagingSenderId: '878896224913',
    projectId: 'travel-journal-beb23',
    databaseURL: 'https://travel-journal-beb23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-beb23.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM0UqyS2fDOEOx1zbZQTpssumm4wUlcas',
    appId: '1:878896224913:ios:316efce5054df4c01abd30',
    messagingSenderId: '878896224913',
    projectId: 'travel-journal-beb23',
    databaseURL: 'https://travel-journal-beb23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-beb23.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVkVUnzA7yyMI991yx1bozPilBA1j4FbQ',
    appId: '1:878896224913:web:3aa72ef940f884041abd30',
    messagingSenderId: '878896224913',
    projectId: 'travel-journal-beb23',
    authDomain: 'travel-journal-beb23.firebaseapp.com',
    databaseURL: 'https://travel-journal-beb23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-beb23.firebasestorage.app',
    measurementId: 'G-E959BTGN7P',
  );

}